baseURL = "http://nvietto.rbind.io/"
theme = "hugo-apero"
languageCode = "en"
title = "Nicholas Vietto "
author = "Nicholas Vietto"
copyright = "" 
googleAnalytics = ""
disqusShortname = ""
metaDataFormat = "yaml"
footnoteReturnLinkContents = "&#8617;" # ↩
# set deliberately low for testing choose your preffered number based on the blog layout you've chosen
paginate = 5
preserveTaxonomyNames = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
    hardwraps = false 
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false
  [markup.highlight]
    # one of: https://xyproto.github.io/splash/docs/ 
    style = "github"
    
[params]
  orgName = "Nicholas Vietto"
  orgLocal = ""
  description = "A personal website."
  favicon = "/img/sharingimg.ico"
  logo = ""
  mainSections = ["blog", "project", "talk"]
  navallcaps = true
  socialInHeader = false
  socialInFooter = true
  sharing_image = [img/sharingimg.png]
  twitter = "ViettoNicholas"
  
  # use a built-in color theme
  # one of: earth / forest / grayscale / magma / paper / peach / plum /
  #         poppy / primer / sky / violet / water 
  theme = "water"
  
  # or, leave theme empty & make your own palette
  # see docs at https://hugo-apero.netlify.app/blog/color-themes/
  # the custom scss file must be in the assets/ folder
  # add the filename name here, without extension
  # to use hex colors instead of named tachyons colors, include "hex" in filename
  custom_theme = "" 
  
  # use an embedded font-family
  # serif options: Fraunces / EB Garamond / Bitter
  # sans-serif options: Commissioner / Atkinson Hyperlegible / Metropolis
  # if you import your own fonts, name them here too
  customtextFontFamily = "Atkinson Hyperlegible "
  customheadingFontFamily = "Metropolis"
  # alternatively, leave empty and select basic font options: sans-serif or serif
  # for more http://tachyons.io/docs/typography/font-family/
  textFontFamily = "sans-serif"
  headingFontFamily = "sans-serif"

  # Configuration of https://utteranc.es/ for comments
  [params.utterances]
    use_utterances = true
    repo_name = "apreshill/apero"
    issue_term = "pathname" # url, pathname, or title
    theme = "boxy-light"
    label = "comments :crystal_ball:"

  # Configuration of math rendering
  [params.math]
    renderer = "katex" # one of "mathjax" / "katex" 

  # Social icons may appear on homepage and in site header or footer
  # Configure show/hide above - add as many as you like below
  # Icon pack "fab" includes brand icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
  # Icon pack "fas" includes solid icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
  # Icon pack "far" includes regular icons, see: https://fontawesome.com/icons?d=gallery&s=regular&m=free
  [[params.social]]
      icon      = "github" 
      icon_pack = "fab"
      url       = "https://github.com/nvietto"
  [[params.social]]
      icon      = "google-scholar" 
      icon_pack = "ai"
      url       = "https://scholar.google.com/citations?user=de7ScEsAAAAJ&hl=en&oi=ao"
  [[params.social]]
      icon      = "linkedin" 
      icon_pack = "fab"
      url       = "http://www.linkedin.com/in/nicholas-vietto"
  [[params.social]]
      icon      = "mastodon"
      icon_pack = "fab"
      url       = "https://fosstodon.org/@nvietto"
  [[params.social]]
      icon      = "twitter" 
      icon_pack = "fab"
      url       = "https://twitter.com/ViettoNicholas"
  [[params.social]]
      icon      = "orcid" 
      icon_pack = "ai"
      url       = "https://orcid.org/0000-0001-8835-2622"
  [[params.social]]
      icon      = "cv" 
      icon_pack = "ai"
      url       = "/img/cv.pdf"
  [[params.social]]
      icon      = "file" 
      icon_pack = "far"
      url       = "/img/Resume.pdf"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[menu]
  # Configure header 
  [[menu.header]]
    name = "About"
    title = "About"
    url = "/"
    weight = 1
  [[menu.header]]
    name = "Blog"
    title = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.header]]
    name = "Talks"
    title = "Talks"
    url = "/talk/"
    weight = 3
  [[menu.header]]
    name = "Data Visualizations"
    title = "Data Visualizations"
    url = "/viz/"
    weight = 4

    
# see https://gohugo.io/about/hugo-and-gdpr/    
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
